app = 'lsl-camera-little-glade-2085'
primary_region = 'cdg'

[build]

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
